import Link from 'next/link';
import { Heart, Search } from 'lucide-react';
import { Container } from './Container';
import { BrandLogo } from './BrandLogo';
import { MobileNavigation } from './MobileNavigation';

const links = [{ href: '/plans', label: 'Уровни' }, { href: '/exams', label: 'Экзамены' }, { href: '/textbooks', label: 'Учебники' }, { href: '/resources', label: 'Ресурсы' }];
const linkClass = 'flex items-center justify-center rounded-md px-2.5 py-2 text-center text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2';
export function SiteHeader() { return <header className="sticky top-0 z-50 border-b border-border bg-background/95 pt-[env(safe-area-inset-top)] shadow-[0_1px_0_rgb(0_0_0/0.02)] backdrop-blur supports-[backdrop-filter]:bg-background/85"><Container className="flex h-16 items-center gap-1 sm:gap-4"><Link href="/" aria-label="CortexMap — на главную" className="shrink-0 rounded-md text-primary focus-visible:outline-2 focus-visible:outline-offset-4"><BrandLogo hideNameOnSmallScreens /></Link><nav aria-label="Основная навигация" className="hidden min-w-0 flex-1 sm:flex">{links.map((link) => <Link key={link.href} href={link.href} className={linkClass}>{link.label}</Link>)}</nav><div className="ml-auto flex shrink-0 items-center gap-1 sm:ml-0"><Link href="/search" aria-label="Поиск" className="inline-flex min-h-11 min-w-11 items-center justify-center gap-2 rounded-lg bg-primary px-3 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-2 focus-visible:outline-offset-2"><Search aria-hidden="true" className="h-5 w-5 sm:h-4 sm:w-4" /><span className="hidden xl:inline">Поиск</span></Link><Link href="/favorites" aria-label="Избранное" className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2"><Heart aria-hidden="true" className="h-5 w-5 sm:h-4 sm:w-4" /></Link><MobileNavigation links={links} /></div></Container></header>; }
