import Link from 'next/link';
import { levels } from '@/data';
import { FavoritesButton } from '@/components/catalog/FavoritesButton';
import { CefrLevelIcon } from '@/components/content/CefrLevelIcon';
import { SiteFooter } from '@/components/layout/SiteFooter';
import { SiteHeader } from '@/components/layout/SiteHeader';
import { createRouteMetadata } from '@/lib/metadata';
export const metadata = createRouteMetadata({ title: 'Планы по уровням CEFR', description: 'Грамматика, лексика и языковые навыки для уровней A1–C2 с рекомендациями по учебным материалам.', path: '/plans' });
export default function PlansPage() { return <><SiteHeader /><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><p className="text-sm font-semibold text-primary">CEFR A1–C2</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Планы по уровням CEFR</h1><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">Проверьте, какие темы по грамматике и лексике соответствуют вашему уровню и какие навыки понадобятся для дальнейшей подготовки к экзамену.</p><div className="mt-8 grid gap-4 md:mt-10 md:grid-cols-2 md:gap-5">{levels.map((level) => <article key={level.id} className="rounded-2xl border border-border/80 bg-card p-4 shadow-sm sm:p-6"><div className="flex min-w-0 items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary"><CefrLevelIcon level={level.title} /></span><div className="min-w-0"><h2 className="text-lg font-semibold sm:text-xl"><Link href={`/plans/${level.slug}`} className="hover:text-primary hover:underline">{level.title}: {level.fullName}</Link></h2><p className="mt-1 text-sm text-muted-foreground">Ориентировочный срок: {level.duration}</p></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{level.description}</p><div className="mt-5 flex flex-wrap items-center gap-3"><Link href={`/plans/${level.slug}`} className="inline-flex min-h-11 items-center text-sm font-semibold text-primary hover:underline">Посмотреть темы уровня →</Link><FavoritesButton contentId={level.id} /></div></article>)}</div></main><SiteFooter /></>; }
